export const digits=(value:string)=>value.replace(/\D/g,"");
export function isCpf(value:string){const cpf=digits(value);if(cpf.length!==11||/^(\d)\1+$/.test(cpf))return false;for(let t=9;t<11;t++){let sum=0;for(let i=0;i<t;i++)sum+=Number(cpf[i])*(t+1-i);const check=((sum*10)%11)%10;if(check!==Number(cpf[t]))return false}return true}
export function isCnpj(value:string){const cnpj=digits(value);if(cnpj.length!==14||/^(\d)\1+$/.test(cnpj))return false;const calc=(base:number[])=>{let sum=0;const weights=base.length===12?[5,4,3,2,9,8,7,6,5,4,3,2]:[6,5,4,3,2,9,8,7,6,5,4,3,2];for(let i=0;i<base.length;i++)sum+=base[i]*weights[i];const rest=sum%11;return rest<2?0:11-rest};const nums=[...cnpj].map(Number);return calc(nums.slice(0,12))===nums[12]&&calc(nums.slice(0,13))===nums[13]}
export const isDocument=(value:string,type:"pf"|"pj")=>!value||(type==="pf"?isCpf(value):isCnpj(value));
export const isEmail=(value:string)=>!value||/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(value.trim());
export const isPhone=(value:string)=>{const n=digits(value);return !value||(n.length>=10&&n.length<=13)};
export const isCep=(value:string)=>!value||digits(value).length===8;
export function isPastDate(value:string){if(!value)return true;const date=new Date(`${value}T12:00:00`);return !Number.isNaN(date.getTime())&&date<=new Date()&&date.getFullYear()>=1900}
export function validatePerson(input:{type:string;document:string;email:string;phone:string;birthDate:string;cep:string}){const errors:string[]=[];const type=input.type==="pj"?"pj":"pf";if(!isDocument(input.document,type))errors.push(type==="pf"?"CPF inválido":"CNPJ inválido");if(!isEmail(input.email))errors.push("E-mail inválido");if(!isPhone(input.phone))errors.push("Telefone inválido");if(!isCep(input.cep))errors.push("CEP inválido");if(type==="pf"&&!isPastDate(input.birthDate))errors.push("Data de nascimento inválida");return errors}
export const masks={document(value:string,type:"pf"|"pj"){const n=digits(value).slice(0,type==="pf"?11:14);return type==="pf"?n.replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/,"$1-$2"):n.replace(/(\d{2})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1/$2").replace(/(\d{4})(\d{1,2})$/,"$1-$2")},phone(value:string){const n=digits(value).slice(0,11);return n.replace(/(\d{2})(\d)/,"($1) $2").replace(/(\d{5})(\d{4})$/,"$1-$2")},cep(value:string){return digits(value).slice(0,8).replace(/(\d{5})(\d)/,"$1-$2")}}
