import { Badge, Card, CardTitle, Empty, PageHeader, money, shortDate } from "@/components/ui";
import { db } from "@/db";
import { financialEntries, notifications, products, settings } from "@/db/schema";
import { desc, eq } from "drizzle-orm";
import { BarChart3, CheckCircle2, CreditCard, Mail, MessageCircle, PlugZap, Settings2, Wrench } from "lucide-react";
import { notFound } from "next/navigation";

export const dynamic="force-dynamic";
const info={pdv:{eyebrow:"Balcão",title:"Ponto de Venda",description:"Venda rápida para itens de pronta entrega e serviços de balcão.",icon:CreditCard},servicos:{eyebrow:"Catálogo",title:"Serviços",description:"Serviços de arte, acabamento, instalação e produção sob demanda.",icon:Wrench},whatsapp:{eyebrow:"Canais",title:"WhatsApp",description:"Mensagens comerciais, aprovações e atualizações automáticas.",icon:MessageCircle},email:{eyebrow:"Canais",title:"E-mail",description:"Outbox de propostas e notificações transacionais.",icon:Mail},integracoes:{eyebrow:"Ecossistema",title:"Integrações",description:"Conecte pagamentos, fretes, comunicação e avaliações.",icon:PlugZap},configuracoes:{eyebrow:"Painel de controle",title:"Configurações",description:"Dados da empresa, custos padrão e preferências operacionais.",icon:Settings2},relatorios:{eyebrow:"Inteligência",title:"Relatórios",description:"Indicadores comerciais, financeiros e de rentabilidade.",icon:BarChart3}} as const;
export default async function SectionPage({params}:{params:Promise<{section:string}>}){const {section}=await params;const data=info[section as keyof typeof info];if(!data)notFound();const Icon=data.icon;
 if(section==="whatsapp"||section==="email"){const rows=await db.select().from(notifications).where(eq(notifications.channel,section)).orderBy(desc(notifications.createdAt));return <><PageHeader eyebrow={data.eyebrow} title={data.title} description={data.description}/><Card><CardTitle detail="As mensagens são criadas automaticamente ao enviar uma proposta">Fila de saída</CardTitle>{rows.length?<div className="table-wrap"><table className="table"><thead><tr><th>Destinatário</th><th>Conteúdo</th><th>Criação</th><th>Status</th></tr></thead><tbody>{rows.map(n=><tr key={n.id}><td><strong>{n.recipient}</strong><br/><small>{n.subject}</small></td><td style={{maxWidth:450,overflow:"hidden",textOverflow:"ellipsis"}}>{n.body}</td><td>{shortDate(n.createdAt)}</td><td><Badge tone={n.status==="enviado"?"green":"amber"}>{n.status}</Badge></td></tr>)}</tbody></table></div>:<Empty title="Nenhuma mensagem na fila" description="Envie um orçamento para gerar notificações neste canal."/>}</Card></>}
 if(section==="servicos"){const rows=await db.select().from(products).where(eq(products.kind,"servico"));return <><PageHeader eyebrow={data.eyebrow} title={data.title} description={data.description}/><Card><CardTitle detail="Serviços usam a mesma engenharia de custos dos produtos">Catálogo de serviços</CardTitle>{rows.length?<div className="table-wrap"><table className="table"><thead><tr><th>Serviço</th><th>Categoria</th><th>Custo</th><th>Preço</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><strong>{p.name}</strong><br/><small>{p.sku}</small></td><td>{p.category}</td><td>{money(p.calculatedCost)}</td><td><strong>{money(p.salePrice)}</strong></td></tr>)}</tbody></table></div>:<Empty title="Nenhum serviço cadastrado" description="Cadastre um item do tipo Serviço em Produtos & Precificação."/>}</Card></>}
 if(section==="integracoes"){const apps=[{name:"InfinitePay",desc:"Links e confirmação de pagamentos",ok:false},{name:"SuperFrete",desc:"Cotações e etiquetas de envio",ok:false},{name:"WhatsApp Bridge",desc:"Mensagens e atendimento",ok:true},{name:"SMTP",desc:"Envio de e-mails transacionais",ok:true}];return <><PageHeader eyebrow={data.eyebrow} title={data.title} description={data.description}/><div className="grid-equal">{apps.map(a=><Card key={a.name}><div style={{padding:22,display:"flex",gap:15,alignItems:"center"}}><div className="metric-icon tone-green"><PlugZap size={19}/></div><div style={{flex:1}}><strong style={{fontSize:13}}>{a.name}</strong><p style={{fontSize:10,color:"#7b8981",margin:"4px 0"}}>{a.desc}</p></div><Badge tone={a.ok?"green":"gray"}>{a.ok?"Simulado":"Configurar"}</Badge></div></Card>)}</div></>}
 if(section==="relatorios"){const entries=await db.select().from(financialEntries);const income=entries.filter(e=>e.type==="receber").reduce((s,e)=>s+Number(e.amount),0),cost=entries.filter(e=>e.type==="pagar").reduce((s,e)=>s+Number(e.amount),0);return <><PageHeader eyebrow={data.eyebrow} title={data.title} description={data.description}/><div className="metrics"><Card className="metric"><div className="metric-icon tone-green"><BarChart3 size={20}/></div><div><p>Vendas geradas</p><strong>{money(income)}</strong><small>pedidos aprovados</small></div></Card><Card className="metric"><div className="metric-icon tone-amber"><CreditCard size={20}/></div><div><p>Compras registradas</p><strong>{money(cost)}</strong><small>custos de insumo</small></div></Card><Card className="metric"><div className="metric-icon tone-blue"><CheckCircle2 size={20}/></div><div><p>Resultado bruto</p><strong>{money(income-cost)}</strong><small>antes das despesas fixas</small></div></Card></div><Card><CardTitle detail="Comparativo financeiro acumulado">Resultado operacional</CardTitle><div className="chart-wrap"><div className="cost-breakdown"><div className="cost-row"><span>Receita em pedidos</span><strong>{money(income)}</strong></div><div className="cost-row"><span>Compras de material</span><strong>− {money(cost)}</strong></div><div className="cost-row total"><span>Resultado bruto</span><strong>{money(income-cost)}</strong></div></div></div></Card></>}
 if(section==="configuracoes"){const [row]=await db.select().from(settings).limit(1);return <><PageHeader eyebrow={data.eyebrow} title={data.title} description={data.description}/><div className="grid-equal"><Card><CardTitle detail="Identidade usada em propostas e mensagens">Dados da empresa</CardTitle><div className="form"><div className="cost-row"><span>Nome</span><strong>{row?.companyName||"PrintFlow"}</strong></div><div className="cost-row"><span>Documento</span><strong>{row?.document||"Não configurado"}</strong></div><div className="cost-row"><span>E-mail</span><strong>{row?.email||"Não configurado"}</strong></div><div className="cost-row"><span>Telefone</span><strong>{row?.phone||"Não configurado"}</strong></div></div></Card><Card><CardTitle detail="Referências usadas na precificação">Parâmetros de custos</CardTitle><div className="form"><div className="cost-row"><span>Margem padrão</span><strong>{Number(row?.defaultMargin||30)}%</strong></div><div className="cost-row"><span>Hora de trabalho</span><strong>{money(row?.hourlyLaborCost||35)}</strong></div></div></Card></div></>}
 return <><PageHeader eyebrow={data.eyebrow} title={data.title} description={data.description}/><Card><Empty title="Módulo preparado para a próxima operação" description="A estrutura está conectada ao núcleo de clientes, produtos, estoque e pedidos."/></Card></>}
