"use client";
import { saveCompanySettings } from "@/app/actions";
import { Building2, Calculator, FileCheck2, LayoutTemplate, Mail, PlugZap, Receipt, Search } from "lucide-react";
import { useState } from "react";
import { ModuleConfigs } from "./module-configs";
import { LandingSettings } from "./landing-settings";
import { CompanyLogoField } from "./company-logo-field";
import { Field, Submit } from "./ui";

type Config = Record<string, Record<string, string | number | boolean>>;
type Setting={companyName:string;tradeName:string|null;logoUrl:string|null;document:string|null; stateRegistration:string|null; municipalRegistration:string|null; taxRegime:string|null; cnae:string|null; email:string|null; phone:string|null; mobile:string|null; website:string|null; address:string|null; neighborhood:string|null; city:string|null; uf:string|null; cep:string|null; receiptFooter:string|null; defaultMargin:string; hourlyLaborCost:string;orderPrefix:string;orderNextNumber:number;orderNumberPadding:number;landingPage:Record<string,string|boolean>|null;integrations:Config|null;communications:Config|null };
const tabs=[{id:"empresa",label:"Empresa",icon:Building2},{id:"fiscal",label:"Fiscal",icon:FileCheck2},{id:"custos",label:"Custos",icon:Calculator},{id:"documentos",label:"Cupom e documentos",icon:Receipt},{id:"pagina",label:"Página pública",icon:LayoutTemplate},{id:"comunicacao",label:"Comunicação",icon:Mail},{id:"integracoes",label:"Integrações",icon:PlugZap}];
export function ControlPanel({row,initialTab="empresa"}:{row:Setting;initialTab?:string}){
 const [tab,setTab]=useState(initialTab);
 const [address,setAddress]=useState({address:row.address||"",neighborhood:row.neighborhood||"",city:row.city||"",uf:row.uf||"",cep:row.cep||""});
 async function cep(){const r=await fetch(`/api/cep/${address.cep}`);if(r.ok)setAddress({...address,...await r.json()})}
 return <div className="control-panel"><aside>{tabs.map(t=>{const Icon=t.icon;return <button className={tab===t.id?"active":""} key={t.id} onClick={()=>setTab(t.id)}><Icon/>{t.label}</button>})}</aside><section>
  {tab==="pagina"?<><Title title="Página pública de cadastro" detail="Banner, textos, redes sociais e Google Reviews"/><LandingSettings value={row.landingPage||{}}/></>:tab==="comunicacao"?<><Title title="Comunicação" detail="Configuração independente de cada canal"/><ModuleConfigs section="communications" config={row.communications||{}}/></>:tab==="integracoes"?<><Title title="Integrações" detail="Cada provedor ligado ao seu módulo do ERP"/><ModuleConfigs section="integrations" config={row.integrations||{}}/></>:<form action={saveCompanySettings} className="form control-form"><Preserve row={row} address={address}/>
   {tab==="empresa"&&<><Title title="Empresa e identidade visual" detail="Logo e dados usados em propostas, pedidos, cupom e documentos"/><CompanyLogoField initialUrl={row.logoUrl}/><div className="form-grid"><Field label="Razão social"><input name="companyName" defaultValue={row.companyName}/></Field><Field label="Nome fantasia"><input name="tradeName" defaultValue={row.tradeName||""}/></Field><Field label="CNPJ"><input name="document" defaultValue={row.document||""}/></Field><Field label="E-mail"><input name="email" defaultValue={row.email||""}/></Field><Field label="Telefone"><input name="phone" defaultValue={row.phone||""}/></Field><Field label="Celular"><input name="mobile" defaultValue={row.mobile||""}/></Field><Field label="Site"><input name="website" defaultValue={row.website||""}/></Field><Field label="CEP"><div className="input-action"><input name="cep" value={address.cep} onChange={e=>setAddress({...address,cep:e.target.value})}/><button type="button" onClick={cep}><Search/></button></div></Field><Field label="Endereço"><input name="address" value={address.address} onChange={e=>setAddress({...address,address:e.target.value})}/></Field><Field label="Bairro"><input name="neighborhood" value={address.neighborhood} onChange={e=>setAddress({...address,neighborhood:e.target.value})}/></Field><Field label="Cidade"><input name="city" value={address.city} onChange={e=>setAddress({...address,city:e.target.value})}/></Field><Field label="UF"><input name="uf" value={address.uf} onChange={e=>setAddress({...address,uf:e.target.value})}/></Field></div></>}
   {tab==="fiscal"&&<><Title title="Dados fiscais" detail="Preparação para NFC-e, NF-e e NFS-e"/><div className="form-grid"><Field label="CNPJ"><input name="document" defaultValue={row.document||""}/></Field><Field label="Inscrição estadual"><input name="stateRegistration" defaultValue={row.stateRegistration||""}/></Field><Field label="Inscrição municipal"><input name="municipalRegistration" defaultValue={row.municipalRegistration||""}/></Field><Field label="Regime tributário"><select name="taxRegime" defaultValue={row.taxRegime||"simples_nacional"}><option value="mei">MEI</option><option value="simples_nacional">Simples Nacional</option><option value="lucro_presumido">Lucro Presumido</option><option value="lucro_real">Lucro Real</option></select></Field><Field label="CNAE principal"><input name="cnae" defaultValue={row.cnae||""}/></Field></div><div className="fiscal-warning">CSC, séries, certificado A1, NCM, CFOP e regras fiscais serão ativados na homologação.</div></>}
   {tab==="custos"&&<><Title title="Custos padrão" detail="Referências para novas fichas técnicas"/><div className="form-grid"><Field label="Margem padrão %"><input name="defaultMargin" type="number" step=".01" defaultValue={row.defaultMargin}/></Field><Field label="Hora de trabalho"><input name="hourlyLaborCost" type="number" step=".01" defaultValue={row.hourlyLaborCost}/></Field><Field label="Prefixo do pedido"><input name="orderPrefix" defaultValue={row.orderPrefix}/></Field><Field label="Próximo número"><input name="orderNextNumber" type="number" defaultValue={row.orderNextNumber}/></Field><Field label="Quantidade de dígitos"><input name="orderNumberPadding" type="number" min="3" max="10" defaultValue={row.orderNumberPadding}/></Field></div></>}
   {tab==="documentos"&&<><Title title="Cupom e documentos" detail="Personalização dos documentos operacionais"/><Field label="Mensagem do rodapé"><textarea name="receiptFooter" defaultValue={row.receiptFooter||""}/></Field><div className="settings-status"><span>✓ Cupom não fiscal 80 mm</span><span>✓ Ordem de produção A4</span><span>◷ NFC-e futura</span><span>◷ NF-e e NFS-e futuras</span><a className="button button-secondary" href="/api/docs/manual" target="_blank">Abrir Manual do Sistema (PDF)</a></div></>}
   <div className="form-actions"><Submit>Salvar Painel de Controle</Submit></div>
  </form>}
 </section></div>
}
function Title({title,detail}:{title:string;detail:string}){return <div className="control-title"><h2>{title}</h2><p>{detail}</p></div>}
function Preserve({row,address}:{row:Setting;address:{address:string;neighborhood:string;city:string;uf:string;cep:string}}){return <>{Object.entries({companyName:row.companyName,tradeName:row.tradeName,logoUrl:row.logoUrl,document:row.document,stateRegistration:row.stateRegistration,municipalRegistration:row.municipalRegistration,taxRegime:row.taxRegime,cnae:row.cnae,email:row.email,phone:row.phone,mobile:row.mobile,website:row.website,address:address.address,neighborhood:address.neighborhood,city:address.city,uf:address.uf,cep:address.cep,receiptFooter:row.receiptFooter,defaultMargin:row.defaultMargin,hourlyLaborCost:row.hourlyLaborCost,orderPrefix:row.orderPrefix,orderNextNumber:row.orderNextNumber,orderNumberPadding:row.orderNumberPadding}).map(([k,v])=><input type="hidden" name={k} value={String(v??"")} key={k}/>)}</>}
