"use client";
import { addProduct } from "@/app/actions";
import { Plus, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { Field, Submit, money } from "./ui";

type Material={id:number;name:string;sku:string;unit:string;stock:string;averageCost:string};
type Printer={id:number;name:string;model:string|null;technology?:string;acquisitionCost:string;usefulLifeMonths:number;monthlyVolume:number;maintenanceMonthly:string;energyCostHour:string;bwCost:string;colorCost:string;hourlyCost:string;pricingData:Record<string,number|string>|null};
type ServiceTier={id:number;label:string;sheetWidthCm:string;sheetHeightCm:string;price:string;serviceName:string;pricingMethod?:string};
type Preview={materials:number;outsourced:number;machine:number;labor:number;setup:number;direct:number;adjusted:number;sale:number};
export function ProductForm({materials,printers,serviceTiers=[]}:{materials:Material[];printers:Printer[];serviceTiers?:ServiceTier[]}){
 const [query,setQuery]=useState("");const [selected,setSelected]=useState<number[]>([]);const [preview,setPreview]=useState<Preview>({materials:0,outsourced:0,machine:0,labor:0,setup:0,direct:0,adjusted:0,sale:0});
 function recalculate(form:HTMLFormElement){const f=new FormData(form),n=(key:string)=>Number(f.get(key)||0)||0;let materialCost=0;for(const material of materials){const quantity=n(`material_${material.id}`),waste=n(`waste_${material.id}`);materialCost+=quantity*(1+waste/100)*Number(material.averageCost)}let outsourced=0;const tier=serviceTiers.find(t=>t.id===n("outsourcedTierId")),aw=n("artworkWidthCm"),ah=n("artworkHeightCm"),gap=n("serviceGap")||.3;if(tier&&aw>0&&ah>0){if(tier.pricingMethod==="per_m2")outsourced=(aw/100)*(ah/100)*Number(tier.price);else{const normal=Math.floor(Number(tier.sheetWidthCm)/(aw+gap))*Math.floor(Number(tier.sheetHeightCm)/(ah+gap)),rotated=Math.floor(Number(tier.sheetWidthCm)/(ah+gap))*Math.floor(Number(tier.sheetHeightCm)/(aw+gap));outsourced=Number(tier.price)/Math.max(1,normal,rotated)}}const printer=printers.find(p=>p.id===n("printerId"));let machine=0;if(printer){const fixed=Number(printer.acquisitionCost)/Math.max(1,printer.usefulLifeMonths*printer.monthlyVolume)+Number(printer.maintenanceMonthly)/Math.max(1,printer.monthlyVolume),clicks=n("printsPerUnit")||1,coverage=n("coveragePercent")||5,mode=String(f.get("printMode")||"color"),variable=mode==="bw"?Number(printer.bwCost):Number(printer.colorCost);if(["laser","inkjet","sublimation"].includes(printer.technology||""))machine=clicks*(variable*(coverage/5)+fixed);else if(printer.technology==="thermal")machine=n("consumableUsage")*variable+clicks*fixed;else machine=(n("machineMinutes")/60)*(Number(printer.hourlyCost)+Number(printer.energyCostHour))+clicks*fixed}const secondary=printers.find(p=>p.id===n("secondaryPrinterId"));if(secondary)machine+=n("secondaryMinutes")*Number(secondary.pricingData?.cutMinute||0)+n("secondaryPasses")*Number(secondary.pricingData?.cutPass||0)+(n("secondaryMinutes")/60)*Number(secondary.hourlyCost);const labor=n("laborMinutes")/60*n("laborHourCost"),setup=n("extraCost")+n("setupCost")/Math.max(1,n("minimumQuantity")||1),direct=materialCost+outsourced+machine+labor+setup,adjusted=direct/Math.max(.1,1-Math.min(90,n("failurePercent"))/100),rates=n("taxPercent")+n("cardFeePercent")+n("commissionPercent")+n("marginPercent"),sale=rates<100?adjusted/(1-rates/100):adjusted*2;setPreview({materials:materialCost,outsourced,machine,labor,setup,direct,adjusted,sale})}
 const found=useMemo(()=>materials.filter(m=>!selected.includes(m.id)&&(m.name+" "+m.sku).toLowerCase().includes(query.toLowerCase())).slice(0,6),[materials,query,selected]);
 return <form action={addProduct} className="form product-pricing-form" onInput={e=>recalculate(e.currentTarget)}><div className="form-grid"><Field label="SKU"><input name="sku" required placeholder="CAR-VIS-4X0"/></Field><Field label="Nome"><input name="name" required/></Field><Field label="Tipo"><select name="kind"><option value="produto">Produto</option><option value="servico">Serviço</option></select></Field><Field label="Categoria"><input name="category" required/></Field><Field label="Quantidade mínima"><input name="minimumQuantity" type="number" step=".01" defaultValue="1"/></Field><Field label="Custo de setup por lote"><input name="setupCost" type="number" step=".01" defaultValue="0"/></Field><Field label="Prazo de produção (dias úteis)"><input name="leadTimeDays" type="number" min="1" defaultValue="3"/></Field></div><div className="live-price-preview"><div><p className="eyebrow">Prévia de custo em tempo real</p><h3>{money(preview.sale)}</h3><span>Preço sugerido por unidade base</span></div><div className="live-cost-lines"><span>Materiais <b>{money(preview.materials)}</b></span><span>Terceirização <b>{money(preview.outsourced)}</b></span><span>Máquina <b>{money(preview.machine)}</b></span><span>Mão de obra <b>{money(preview.labor)}</b></span><span>Setup e extras <b>{money(preview.setup)}</b></span><span>Custo ajustado <b>{money(preview.adjusted)}</b></span></div></div>
 <p className="eyebrow" style={{marginTop:24}}>1 • Material vem do estoque</p><div className="material-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar papel, filamento, embalagem, acabamento..."/></div>{query&&<div className="search-results">{found.map(m=><button type="button" key={m.id} onClick={()=>{setSelected(s=>[...s,m.id]);setQuery("")}}><span><strong>{m.name}</strong><small>{m.sku} • saldo {Number(m.stock).toLocaleString("pt-BR")} {m.unit}</small></span><span>{money(m.averageCost)}/{m.unit} <Plus size={14}/></span></button>)}</div>}
 <div className="selected-materials">{selected.length===0?<div className="empty-inline">Busque acima e adicione um ou mais materiais à composição.</div>:selected.map((id,index)=>{const m=materials.find(x=>x.id===id)!;return <div className="selected-material" key={id}><div className="material-index">{index+1}</div><div className="material-info"><strong>{m.name}</strong><span>{m.sku} • {money(m.averageCost)}/{m.unit}</span></div><Field label={`Consumo (${m.unit})`}><input name={`material_${m.id}`} type="number" step=".0001" defaultValue="1" required/></Field><Field label="Perda / refil %"><input name={`waste_${m.id}`} type="number" step=".01" defaultValue="0"/></Field><button className="icon-danger" type="button" onClick={()=>setSelected(s=>s.filter(x=>x!==id))}><Trash2 size={15}/></button></div>})}</div>
 <p className="eyebrow" style={{marginTop:24}}>2 • Serviço terceirizado (opcional)</p><div className="form-grid"><Field label="Tabela DTF / parceiro"><select name="outsourcedTierId"><option value="">Sem terceirização</option>{serviceTiers.map(t=><option key={t.id} value={t.id}>{t.serviceName} • {t.label} • {money(t.price)}</option>)}</select></Field><Field label="Largura da arte (cm)"><input name="artworkWidthCm" type="number" step=".1"/></Field><Field label="Altura da arte (cm)"><input name="artworkHeightCm" type="number" step=".1"/></Field><Field label="Espaçamento / sangria (cm)"><input name="serviceGap" type="number" step=".1" defaultValue="0.3"/></Field></div><p className="form-help">O sistema testa encaixe normal e rotacionado, divide o preço da folha pelo total de estampas e soma ao material escolhido acima.</p>
 <p className="eyebrow" style={{marginTop:24}}>3 • Mão de obra e máquina</p><div className="form-grid"><Field label="Equipamento"><select name="printerId"><option value="">Sem máquina</option>{printers.map(p=><option key={p.id} value={p.id}>{p.name} {p.model&&`— ${p.model}`}</option>)}</select></Field><Field label="Formato / folha"><select name="paperSize"><option>A4 — 210 × 297 mm</option><option>A3 — 297 × 420 mm</option><option>A5 — 148 × 210 mm</option><option>SRA3 — 320 × 450 mm</option><option>Bobina / personalizado</option></select></Field><Field label="Impressão"><select name="printMode"><option value="color">Colorida</option><option value="bw">Preto e branco</option></select></Field><Field label="Páginas / cliques por peça"><input name="printsPerUnit" type="number" step=".01" defaultValue="1"/></Field><Field label="Cobertura de tinta/toner"><select name="coveragePercent"><option value="5">5% — texto/referência</option><option value="30">30% — arte leve</option><option value="50">50% — arte média</option><option value="100">100% — fundo cheio/foto</option></select></Field><Field label="Ribbon por unidade (metros)" hint="Para térmica: altura da etiqueta + GAP em metros"><input name="consumableUsage" type="number" step=".00001" defaultValue="0"/></Field><Field label="Minutos de máquina"><input name="machineMinutes" type="number" step=".01" defaultValue="0"/></Field><Field label="Minutos de mão de obra"><input name="laborMinutes" type="number" step=".01" defaultValue="5"/></Field><Field label="Valor da hora"><input name="laborHourCost" type="number" step=".01" defaultValue="35"/></Field><Field label="Falha técnica / refação %"><input name="failurePercent" type="number" step=".01" defaultValue="0"/></Field><Field label="Gramas por peça (3D)" hint="Converte automaticamente para fração do rolo de 1 kg"><input name="weightGrams" type="number" step=".001" defaultValue="0"/></Field><Field label="Custos extras"><input name="extraCost" type="number" step=".01" defaultValue="0"/></Field></div><p className="eyebrow" style={{marginTop:18}}>Processo adicional — corte/acabamento</p><div className="form-grid"><Field label="Segundo equipamento"><select name="secondaryPrinterId"><option value="">Sem processo adicional</option>{printers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Minutos de corte"><input name="secondaryMinutes" type="number" step=".1" defaultValue="0"/></Field><Field label="Passes / peças"><input name="secondaryPasses" type="number" step=".1" defaultValue="0"/></Field></div>
 <p className="eyebrow" style={{marginTop:24}}>3 • Margem, taxas e preço</p><div className="form-grid"><Field label="Margem líquida %"><input name="marginPercent" type="number" step=".01" defaultValue="30"/></Field><Field label="Impostos %"><input name="taxPercent" type="number" step=".01" defaultValue="6"/></Field><Field label="Taxa cartão %"><input name="cardFeePercent" type="number" step=".01" defaultValue="3.49"/></Field><Field label="Comissão %"><input name="commissionPercent" type="number" step=".01" defaultValue="0"/></Field></div>
 <p className="eyebrow" style={{marginTop:24}}>4 • Frete e faixas de quantidade</p><div className="form-grid"><Field label="Peso (kg)"><input name="shippingWeight" type="number" step=".001"/></Field><Field label="Altura (cm)"><input name="heightCm" type="number" step=".1"/></Field><Field label="Largura (cm)"><input name="widthCm" type="number" step=".1"/></Field><Field label="Comprimento (cm)"><input name="lengthCm" type="number" step=".1"/></Field></div><div className="tier-grid">{[1,2,3].map(i=><div key={i}><span>Faixa {i}</span><input name={`tierFrom_${i}`} type="number" placeholder="A partir de"/><input name={`tierDiscount_${i}`} type="number" step=".01" placeholder="Desconto %"/></div>)}</div>
 <div className="cost-breakdown"><div className="cost-row"><span>Preço automático</span><strong>(materiais + máquina + mão de obra + setup + falhas) ÷ divisor comercial</strong></div></div><div className="form-actions"><Submit>Calcular e salvar item</Submit></div></form>
}
