import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';import {mkdir,writeFile} from 'node:fs/promises';
const sections=[
['1. Visão geral','PrintFlow ERP integra gráfica rápida, papelaria personalizada, brindes, sublimação e impressão 3D. O fluxo principal é: captação > CRM > ficha técnica > orçamento > aprovação > pedido > Kanban > logística > financeiro > pós-venda.'],
['2. Acesso e segurança','A área administrativa exige login. O primeiro administrador é criado em /primeiro-acesso com ADMIN_SETUP_TOKEN. Senhas usam bcrypt, sessões expiram em 8 horas, cookies são HttpOnly e SameSite Strict, e a conta bloqueia após cinco tentativas. Use sempre HTTPS.'],
['3. CRM e pré-cadastros','Cadastros PF/PJ validam CPF/CNPJ, e-mail, telefone, CEP e nascimento. A página /cadastro é pública e isolada. Entradas de WhatsApp, site, balcão e API externa chegam em Pré-cadastros e são convertidas para o CRM. Consentimentos promocionais são separados por canal.'],
['4. Estoque e compras','Materiais possuem categoria e SKU por variação. Papéis controlam formato, acabamento, gramatura, resma e custo por folha. Camisas controlam tamanho e cor. Etiquetas controlam dimensões, GAP, quantidade e metragem. Compras atualizam custo médio e geram conta a pagar.'],
['5. Impressoras e precificação','Categorias tecnológicas são isoladas: Laser, Jato, Térmica, Sublimação, Plotter e 3D. Cobertura de toner/tinta usa custo nominal x cobertura real / 5. Custos fixos não escalam pela cobertura. Papel e filamento vêm do estoque. Produtos podem combinar impressão, corte e terceirização.'],
['6. Terceirização','DTF UV e Têxtil usam aproveitamento normal/rotacionado. Banner e vinil usam largura x altura em metros x preço do fornecedor por m2. Reajustes são feitos em Serviços e Tabelas. O custo terceirizado entra na ficha do produto antes de taxas e margem.'],
['7. Produtos e serviços','A ficha técnica soma materiais, desperdício, impressão, equipamento secundário, terceirização, mão de obra, setup, falhas e extras. O preço divide o custo pelo divisor comercial para recuperar impostos, cartão, comissão e margem. Cada item possui prazo de produção.'],
['8. Orçamento e pedido','O orçamento é enviado por e-mail/WhatsApp com link e PDF. A aprovação reserva número configurável, gera pedido, prazo, conta a receber, Kanban e acompanhamento público. O cliente acompanha em /acompanhar/[token].'],
['9. PDV e caixa','O PDV aceita desconto fixo/percentual, faixas de quantidade, acréscimo, parcelas, autorização e conta de recebimento. Pode gerar somente cupom ou também pedido de produção. Caixa do PDV possui abertura, suprimento, sangria, entrada automática, fechamento e diferença.'],
['10. Financeiro','Contas gerenciáveis incluem Caixa, Banco Inter, InfinitePay e outras. Há transferências entre contas, tarifas, contas a pagar/receber, competência, vencimento, categorias, centro de custo, inadimplência, aging, saldos e projeção.'],
['11. Produção e logística','O Kanban funciona por arrastar e soltar e dispara templates. A logística organiza Balcão, 99Entrega, Uber Entrega e SuperFrete. Registra motorista, custo, coleta, rastreio e entrega. A entrega confirmada dispara pós-venda.'],
['12. Impressão e PDFs','A Central de Impressão gera etiqueta térmica interna, ordem A4 e PDF. Cupom não fiscal usa 80 mm. Orçamento e pedido possuem PDFs compartilháveis. Documentos fiscais aguardam homologação contábil.'],
['13. WhatsApp e e-mail','Templates possuem preview ao vivo e placeholders. Campanhas são restritas a clientes liberados e consentidos. WhatsApp usa bridge externa por QR, fila, intervalo, limite, horário e handoff humano. Para alto volume, prefira Meta Cloud API.'],
['14. API externa','/api/external usa Bearer EXTERNAL_API_TOKEN. Permite consultar clientes/pedidos e receber eventos ou leads com deduplicação por externalId. Use HTTPS e restrição por IP. O ERP não hospeda telefonia.'],
['15. Relatórios','Relatórios possuem período, atualização a cada 30 segundos, CSV e impressão/PDF. Acompanham vendas, ticket, margem, estoque, canais, produtos, produção e caixa.'],
['16. Implantação','Configure DATABASE_URL, NEXT_PUBLIC_APP_URL, ADMIN_SETUP_TOKEN, SMTP, WhatsApp, pagamentos, fretes e API externa. Ative TLS, backups, monitoramento, rate limit no proxy, usuário PostgreSQL restrito, SPF/DKIM/DMARC e política LGPD. Consulte docs/PRODUCTION_CHECKLIST.md.'],
['17. Rotina recomendada','Abra o caixa, confira filas e estoque, processe orçamentos, acompanhe Kanban, imprima ordens, organize entregas, concilie contas e feche o caixa. Faça backup diário e teste restauração periodicamente.']
];
const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page,y;function newPage(){page=pdf.addPage([595,842]);page.drawRectangle({x:0,y:810,width:595,height:32,color:rgb(.06,.62,.82)});page.drawText('PRINTFLOW ERP - MANUAL DO SISTEMA',{x:36,y:820,font:bold,size:11,color:rgb(1,1,1)});page.drawText('Versão operacional 2026',{x:450,y:820,font,size:7,color:rgb(1,1,1)});y=780}function wrap(text,max=92){const words=text.split(/\s+/),lines=[];let line='';for(const w of words){if((line+' '+w).length>max){lines.push(line);line=w}else line+=(line?' ':'')+w}if(line)lines.push(line);return lines}newPage();page.drawText('Manual técnico e operacional',{x:36,y,font:bold,size:24,color:rgb(.05,.14,.24)});y-=35;page.drawText('Gráfica rápida, personalizados, sublimação e impressão 3D',{x:36,y,font,size:11,color:rgb(.25,.35,.45)});y-=45;for(const [title,body] of sections){if(y<110)newPage();page.drawText(title,{x:36,y,font:bold,size:13,color:rgb(.04,.48,.68)});y-=19;for(const line of wrap(body)){page.drawText(line,{x:36,y,font,size:9,color:rgb(.12,.18,.25)});y-=13}y-=13}for(const [i,p] of pdf.getPages().entries()){p.drawText(`PrintFlow ERP | Página ${i+1} de ${pdf.getPageCount()} | Documento interno`,{x:36,y:24,font,size:7,color:rgb(.45,.5,.55)})}await mkdir('docs',{recursive:true});await writeFile('docs/Manual-PrintFlow-ERP.pdf',await pdf.save());console.log('Manual PDF gerado:',pdf.getPageCount(),'páginas');
